
/*Crea la tabla de alumnos con los campos id (PK), DNI, nombre, apellido e email*/
CREATE TABLE IF NOT EXISTS ALUMNOS(
    ID INTEGER PRIMARY KEY,
    DNI INTEGER UNIQUE NOT NULL,
    NOMBRE_APELLIDO VARCHAR(50) NOT NULL,
    CURSO VARCHAR(2) NOT NULL,
    EMAIL VARCHAR(320)
);

CREATE TABLE IF NOT EXISTS ALUMNOS_HISTORICOS(
    ID INTEGER PRIMARY KEY,
    DNI INTEGER UNIQUE NOT NULL,
    NOMBRE_APELLIDO VARCHAR(50) NOT NULL,
    CURSO VARCHAR(2) NOT NULL,
    FECHA_SALIDA VARCHAR(10) NOT NULL,
    EMAIL VARCHAR(320)
);
/*Crea la tabla de herramientas con los campos id (PK), descripción, cantidad en condiciones,
cantidad en reparación, cantidad de baja, id de grupo e id de subgrupo.*/
CREATE TABLE IF NOT EXISTS HERRAMIENTAS(
    ID INTEGER PRIMARY KEY,
    DESC_LARGA VARCHAR(100) NOT NULL,
    CANT_CONDICIONES INTEGER,
    CANT_REPARACION INTEGER,
    CANT_BAJA INTEGER,
    GRUPO VARCHAR(50),
    SUBGRUPO VARCHAR(50),
    FOREIGN KEY(GRUPO) REFERENCES GRUPOS(ID) ON DELETE CASCADE,
    FOREIGN KEY(SUBGRUPO) REFERENCES SUBGRUPOS(ID) ON DELETE SET NULL
);

/*Crea la tabla de profesores con los campos id (PK) y nombre y apellido*/
CREATE TABLE IF NOT EXISTS PROFESORES(
    ID INTEGER PRIMARY KEY,
    DNI INTEGER UNIQUE NOT NULL,
    NOMBRE_APELLIDO VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(320)
);

CREATE TABLE IF NOT EXISTS PROFESORES_HISTORICOS(
    ID INTEGER PRIMARY KEY,
    DNI INTEGER UNIQUE NOT NULL,
    NOMBRE_APELLIDO VARCHAR(50) NOT NULL,
    FECHA_PASE VARCHAR(10),
    EMAIL VARCHAR(320)
);

/*Crea la tabla de alumnos con los campos id (PK), fecha, alumno, nombre y apellido y email*/
CREATE TABLE IF NOT EXISTS TURNO_PANOL(
    ID INTEGER PRIMARY KEY,
    FECHA VARCHAR(12),
    ID_ALUMNO INTEGER,
    HORA_INGRESO VARCHAR(12),
    HORA_EGRESO VARCHAR(12),
    PROF_INGRESO INTEGER,
    PROF_EGRESO INTEGER,
    FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNOS(ID) ON DELETE CASCADE,
    FOREIGN KEY (PROF_INGRESO) REFERENCES PROFESORES(ID) ON DELETE CASCADE,
    FOREIGN KEY (PROF_EGRESO) REFERENCES PROFESORES(ID) ON DELETE CASCADE
);

/*Crea la tabla de movimiento de herramientas con los campos id_herramienta, id_alumno, fecha, cantidad, 
tipo (ingreso o devolución y el id del turno del pañol.*/
CREATE TABLE IF NOT EXISTS MOVIMIENTOS_HERRAMIENTAS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_HERRAMIENTA INTEGER,
    ID_ALUMNO INTEGER,
    FECHA VARCHAR(12),
    CANTIDAD INTEGER,
    TIPO VARCHAR(50),
    ID_TURNO_PANOL INTEGER,
    FOREIGN KEY(ID_ALUMNO) REFERENCES ALUMNOS(ID) ON DELETE CASCADE,
    FOREIGN KEY(ID_HERRAMIENTA) REFERENCES HERRAMIENTAS(ID) ON DELETE CASCADE,
    FOREIGN KEY(ID_TURNO_PANOL) REFERENCES TURNO_PANOL(ID) ON DELETE CASCADE
);

/*Crea la tabla de usuarios. Ignorar por ahora*/
CREATE TABLE IF NOT EXISTS USUARIOS(
    ID INTEGER PRIMARY KEY,
    USUARIO VARCHAR(20) NOT NULL,
    CONTRASENA VARCHAR(75),
    NOMBRE_APELLIDO VARCHAR(35)
);

/*Crea la tabla de usuarios. Ignorar por ahora*/
CREATE TABLE IF NOT EXISTS GRUPOS(
    ID VARCHAR(40) PRIMARY KEY
);

/*Crea la tabla de usuarios. Ignorar por ahora*/
CREATE TABLE IF NOT EXISTS SUBGRUPOS(
    ID VARCHAR(40) PRIMARY KEY,
    GRUPO VARCHAR(40),
    FOREIGN KEY(GRUPO) REFERENCES GRUPOS(ID) ON DELETE CASCADE
);