wCREATE TABLE IF NOT EXISTS ALUMNOS(
    ID INTEGER PRIMARY KEY,
    DNI INTEGER UNIQUE NOT NULL,
    NOMBRE_APE_ALUM VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100)
);

CREATE TABLE  IF NOT EXISTS HERRAMIENTAS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DESC_LARGA VARCHAR(100) NOT NULL,
    CANT_CONDICIONES INTEGER,
    CANT_REPARACION INTEGER,
    CANT_BAJA INTEGER,
    ID_GRUPO VARCHAR(50),
    ID_SUBGRUPO VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS  PROFESORES(
    ID INTEGER PRIMARY KEY,
    NOMB_APELLIDO VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS  TURNO_PANOL(
    TURNO_COD INTEGER PRIMARY KEY,
    FECHA VARCHAR(12),
    ALUMNO VARCHAR(50),
    HORA_INGRESO VARCHAR(12),
    HORA_EGRESO VARCHAR(12),
    AUTO_PROF INTEGER,
    FOREIGN KEY (ALUMNO) REFERENCES ALUMNOS
);
CREATE TABLE IF NOT EXISTS  MOV_HERRAMIENTA(
    COD_HERRAMIENTA INTEGER,
    COD_ALUMNO INTEGER,
    FECHA VARCHAR(12),
    CANT INTEGER,
    TIPO_RETIRO_DEVOLUCION INTEGER,
    COD_TURNO_PAÑOL INTEGER,
    FOREIGN KEY(COD_ALUMNO) REFERENCES ALUMNOS(ID),
    FOREIGN KEY(COD_HERRAMIENTA) REFERENCES HERRAMIENTAS(ID)
);

CREATE TABLE IF NOT EXISTS USUARIOS(
    ID INTEGER PRIMARY KEY,
    NOMBRE_APE_ALUM VARCHAR(50) NOT NULL,
    DNI INTEGER UNIQUE NOT NULL,
    EMAIL VARCHAR(100),
    CONTRASENA VARCHAR(20)
);