# Form implementation generated from reading ui file 'c:\Users\Maximo\Documents\Blustock\blustock\uis\main.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(832, 545)
        MainWindow.setStyleSheet("*{\n"
"    font-family: \'Oswald\', sans-serif;\n"
"    font-weight: 400;\n"
"}\n"
"\n"
"QMenuBar{\n"
"    background-color: #293045;\n"
"    padding: 0;    \n"
"    font-size: 14px;\n"
"    color:white;\n"
"}\n"
"\n"
"QMenuBar:item{\n"
"    padding: 17px;\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QMenuBar:item:selected{\n"
"    background-color: #768AC5;\n"
"    color:black;\n"
"    border-radius: 5px;\n"
"    margin: 10px;\n"
"    \n"
"    \n"
"\n"
"}\n"
"\n"
"QMenu{\n"
"    background-color: #293045;\n"
"\n"
"    color: white;\n"
"}\n"
"\n"
"QMenu:item{\n"
"    padding: 5px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QMenu:item:selected{\n"
"    background-color: #768AC5;\n"
"    color:white;\n"
"\n"
"}\n"
"Qmenu#icon{\n"
"   icon:size 40px; \n"
"    \n"
"}\n"
"\n"
"\n"
"QRadioButton:indicator{\n"
"    border-style: solid;\n"
"    border-color:  #293045;\n"
"    border-radius: 6%;\n"
"    border-width:  2px;\n"
"    background-color: #BABFCE;\n"
"}\n"
"QRadioButton::indicator:checked{\n"
"    background-color: #768AC5;\n"
"}\n"
"\n"
"#label{\n"
"    font-size: 35px;\n"
"}\n"
"\n"
"#usuariosLabel{\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"#contraseALabel{\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"#usuariosLineEdit{\n"
"    width: 170px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#passwordLineEdit{\n"
"    width: 170px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#labelprofesores{\n"
"    font-size: 26px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border-radius: 5px;\n"
"    background-color: #BABFCE;\n"
"    \n"
"}\n"
"\n"
"#title{\n"
"    width: 100px;\n"
"    height: 200px;\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton{\n"
"    border-color:#293045;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 6px;\n"
"    background-color: #293045;\n"
"    color:#ffffff;\n"
"    height: 30px;\n"
"    padding: 0px 4px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#768AC5;\n"
"    color:#293045;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #293045;\n"
"\n"
"}\n"
"\n"
"#pushButton_5{\n"
"    padding: 10px;\n"
"    background-color: #768AC5;\n"
"    border-radius: 15%;\n"
"}\n"
"\n"
"#pushButton_2, #pushButton_3, #pushButton_4{\n"
"    height: 30px;\n"
"}\n"
"#pushButton_5 {\n"
"    width: 10px;\n"
"    height: 10px\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.gridLayout_3.addWidget(self.stackedWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 832, 52))
        self.menubar.setObjectName("menubar")
        self.menuHerramientas = QtWidgets.QMenu(self.menubar)
        self.menuHerramientas.setObjectName("menuHerramientas")
        self.menuPersonal = QtWidgets.QMenu(self.menubar)
        self.menuPersonal.setObjectName("menuPersonal")
        self.menuMovimientos = QtWidgets.QMenu(self.menubar)
        self.menuMovimientos.setObjectName("menuMovimientos")
        self.menuTurnos = QtWidgets.QMenu(self.menubar)
        self.menuTurnos.setObjectName("menuTurnos")
        self.menuUsuarios = QtWidgets.QMenu(self.menubar)
        self.menuUsuarios.setObjectName("menuUsuarios")
        self.menuHISTORIAL = QtWidgets.QMenu(self.menubar)
        self.menuHISTORIAL.setObjectName("menuHISTORIAL")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.opcionSubgrupos = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.opcionSubgrupos.setFont(font)
        self.opcionSubgrupos.setObjectName("opcionSubgrupos")
        self.opcionGrupos = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.opcionGrupos.setFont(font)
        self.opcionGrupos.setObjectName("opcionGrupos")
        self.opcionStock = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.opcionStock.setFont(font)
        self.opcionStock.setObjectName("opcionStock")
        self.actionConsultas = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.actionConsultas.setFont(font)
        self.actionConsultas.setObjectName("actionConsultas")
        self.opcionMovimientos = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.opcionMovimientos.setFont(font)
        self.opcionMovimientos.setObjectName("opcionMovimientos")
        self.opcionAlumnos = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.opcionAlumnos.setFont(font)
        self.opcionAlumnos.setObjectName("opcionAlumnos")
        self.actionProfesores = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.actionProfesores.setFont(font)
        self.actionProfesores.setObjectName("actionProfesores")
        self.actionlogo = QtGui.QAction(MainWindow)
        self.actionlogo.setObjectName("actionlogo")
        self.actionaa = QtGui.QAction(MainWindow)
        self.actionaa.setObjectName("actionaa")
        self.opcionOtroPersonal = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.opcionOtroPersonal.setFont(font)
        self.opcionOtroPersonal.setObjectName("opcionOtroPersonal")
        self.opcionUsuarios = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.opcionUsuarios.setFont(font)
        self.opcionUsuarios.setObjectName("opcionUsuarios")
        self.opcionTurnos = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.opcionTurnos.setFont(font)
        self.opcionTurnos.setObjectName("opcionTurnos")
        self.actiona = QtGui.QAction(MainWindow)
        self.actiona.setObjectName("actiona")
        self.actionGesti_n_de_usuarios = QtGui.QAction(MainWindow)
        self.actionGesti_n_de_usuarios.setObjectName("actionGesti_n_de_usuarios")
        self.opcionUsuariosG = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.opcionUsuariosG.setFont(font)
        self.opcionUsuariosG.setObjectName("opcionUsuariosG")
        self.opcionHistorial = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.opcionHistorial.setFont(font)
        self.opcionHistorial.setObjectName("opcionHistorial")
        self.menuHerramientas.addAction(self.opcionStock)
        self.menuHerramientas.addAction(self.opcionSubgrupos)
        self.menuHerramientas.addAction(self.opcionGrupos)
        self.menuPersonal.addAction(self.opcionAlumnos)
        self.menuPersonal.addAction(self.opcionOtroPersonal)
        self.menuMovimientos.addAction(self.opcionMovimientos)
        self.menuTurnos.addAction(self.opcionTurnos)
        self.menuUsuarios.addAction(self.opcionUsuariosG)
        self.menuHISTORIAL.addAction(self.opcionHistorial)
        self.menubar.addAction(self.menuHerramientas.menuAction())
        self.menubar.addAction(self.menuPersonal.menuAction())
        self.menubar.addAction(self.menuTurnos.menuAction())
        self.menubar.addAction(self.menuMovimientos.menuAction())
        self.menubar.addAction(self.menuUsuarios.menuAction())
        self.menubar.addAction(self.menuHISTORIAL.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuHerramientas.setTitle(_translate("MainWindow", "HERRAMIENTAS"))
        self.menuPersonal.setTitle(_translate("MainWindow", "PERSONAL"))
        self.menuMovimientos.setTitle(_translate("MainWindow", "MOVIMIENTOS"))
        self.menuTurnos.setTitle(_translate("MainWindow", "TURNOS"))
        self.menuUsuarios.setTitle(_translate("MainWindow", "USUARIOS"))
        self.menuHISTORIAL.setTitle(_translate("MainWindow", "HISTORIAL"))
        self.opcionSubgrupos.setText(_translate("MainWindow", "Gestión de subgrupos"))
        self.opcionGrupos.setText(_translate("MainWindow", "Gestión de grupos"))
        self.opcionStock.setText(_translate("MainWindow", "Gestión de herramientas e insumos"))
        self.actionConsultas.setText(_translate("MainWindow", "Consultas"))
        self.opcionMovimientos.setText(_translate("MainWindow", "Gestión de movimientos"))
        self.opcionAlumnos.setText(_translate("MainWindow", "Gestión de alumnos"))
        self.actionProfesores.setText(_translate("MainWindow", "Profesores"))
        self.actionlogo.setText(_translate("MainWindow", "logo"))
        self.actionaa.setText(_translate("MainWindow", "aa"))
        self.opcionOtroPersonal.setText(_translate("MainWindow", "Gestión de otro personal"))
        self.opcionUsuarios.setText(_translate("MainWindow", "Gestión de usuarios"))
        self.opcionTurnos.setText(_translate("MainWindow", "Gestión de turnos del pañol"))
        self.actiona.setText(_translate("MainWindow", "a"))
        self.actionGesti_n_de_usuarios.setText(_translate("MainWindow", "Gestión de usuarios"))
        self.opcionUsuariosG.setText(_translate("MainWindow", "Gestión de usuarios"))
        self.opcionHistorial.setText(_translate("MainWindow", "Ver historial"))
