# Form implementation generated from reading ui file 'registroENG.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 1024)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 1024))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 1024))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(-100, 849, 1521, 141))
        self.widget_2.setStyleSheet("background-color:#0d43d4")
        self.widget_2.setObjectName("widget_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(-20, 120, 1301, 741))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_31.setGeometry(QtCore.QRect(645, 255, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_31.setFont(font)
        self.lineEdit_31.setStyleSheet("\n"
"    background-color: rgb(186, 201, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(150, 175, 255) ;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"")
        self.lineEdit_31.setText("")
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.label_40 = QtWidgets.QLabel(self.page_5)
        self.label_40.setGeometry(QtCore.QRect(525, 320, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("font-weight: bold;")
        self.label_40.setObjectName("label_40")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_33.setGeometry(QtCore.QRect(645, 375, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_33.setFont(font)
        self.lineEdit_33.setStyleSheet("    background-color: rgb(186, 201, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(150, 175, 255) ;\n"
"    min-width: 10em;\n"
"    padding: 6px;")
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.label_42 = QtWidgets.QLabel(self.page_5)
        self.label_42.setGeometry(QtCore.QRect(525, 385, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("font-weight: bold;")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.page_5)
        self.label_43.setGeometry(QtCore.QRect(525, 260, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("font-weight: bold;")
        self.label_43.setObjectName("label_43")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_36.setGeometry(QtCore.QRect(645, 315, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_36.setFont(font)
        self.lineEdit_36.setStyleSheet("\n"
"    background-color: rgb(186, 201, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(150, 175, 255) ;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"")
        self.lineEdit_36.setText("")
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.label_46 = QtWidgets.QLabel(self.page_5)
        self.label_46.setGeometry(QtCore.QRect(575, 170, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("")
        self.label_46.setObjectName("label_46")
        self.pushButton_6 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_6.setGeometry(QtCore.QRect(615, 450, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bebas")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("#pushButton_6{    background-color: rgb(13, 67, 212);\n"
"color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#pushButton_6:pressed{     background-color: rgb(0, 20, 212); }")
        self.pushButton_6.setObjectName("pushButton_6")
        self.comboBox_3 = QtWidgets.QComboBox(self.page_5)
        self.comboBox_3.setGeometry(QtCore.QRect(60, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("QComboBox::drop-down {\n"
"    background-color:rgb(220,220,220)\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"    border:none;\n"
"     border-left-width: 1px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"QComboBox{    background-color:rgb(220,220,220)}\n"
"")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.pushButton_9 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_9.setGeometry(QtCore.QRect(540, 520, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: none;\n"
"border:none;\n"
"\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_44 = QtWidgets.QLabel(self.page_6)
        self.label_44.setGeometry(QtCore.QRect(525, 260, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("font-weight: bold;")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.page_6)
        self.label_45.setGeometry(QtCore.QRect(525, 320, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("font-weight: bold;")
        self.label_45.setObjectName("label_45")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_37.setGeometry(QtCore.QRect(645, 315, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_37.setFont(font)
        self.lineEdit_37.setStyleSheet("\n"
"    background-color: rgb(186, 201, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(150, 175, 255) ;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"")
        self.lineEdit_37.setText("")
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.label_47 = QtWidgets.QLabel(self.page_6)
        self.label_47.setGeometry(QtCore.QRect(525, 385, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("font-weight: bold;")
        self.label_47.setObjectName("label_47")
        self.pushButton_7 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_7.setGeometry(QtCore.QRect(615, 450, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bebas")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("#pushButton_7{    background-color: rgb(13, 67, 212);\n"
"color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#pushButton_7:pressed{     background-color: rgb(0, 20, 212); }")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_48 = QtWidgets.QLabel(self.page_6)
        self.label_48.setGeometry(QtCore.QRect(625, 170, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("")
        self.label_48.setObjectName("label_48")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_32.setGeometry(QtCore.QRect(645, 255, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_32.setFont(font)
        self.lineEdit_32.setStyleSheet("\n"
"    background-color: rgb(186, 201, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(150, 175, 255) ;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"")
        self.lineEdit_32.setText("")
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_34.setGeometry(QtCore.QRect(645, 375, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_34.setFont(font)
        self.lineEdit_34.setStyleSheet("    background-color: rgb(186, 201, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(150, 175, 255) ;\n"
"    min-width: 10em;\n"
"    padding: 6px;")
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.comboBox_4 = QtWidgets.QComboBox(self.page_6)
        self.comboBox_4.setGeometry(QtCore.QRect(60, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setStyleSheet("QComboBox::drop-down {\n"
"    background-color:rgb(220,220,220)\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"    border:none;\n"
"     border-left-width: 1px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"QComboBox{    background-color:rgb(220,220,220)}\n"
"")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.pushButton_10 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_10.setGeometry(QtCore.QRect(540, 520, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("background-color: none;\n"
"border:none;\n"
"\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.stackedWidget.addWidget(self.page_6)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_52 = QtWidgets.QLabel(self.page_3)
        self.label_52.setGeometry(QtCore.QRect(500, 100, 381, 61))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("")
        self.label_52.setObjectName("label_52")
        self.label_24 = QtWidgets.QLabel(self.page_3)
        self.label_24.setGeometry(QtCore.QRect(520, 320, 146, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("font-weight: bold;")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.page_3)
        self.label_25.setGeometry(QtCore.QRect(700, 320, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.page_3)
        self.label_26.setGeometry(QtCore.QRect(520, 400, 146, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("font-weight: bold;")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.page_3)
        self.label_27.setGeometry(QtCore.QRect(700, 400, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 20, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("#pushButton_4{    background-color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#pushButton_4:pressed{     background-color: rgb(0, 20, 212); }")
        self.pushButton_4.setObjectName("pushButton_4")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_18.setGeometry(QtCore.QRect(665, 295, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_18.setFont(font)
        self.lineEdit_18.setStyleSheet("    background-color: rgb(186, 201, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(150, 175, 255) ;\n"
"    min-width: 10em;\n"
"    padding: 6px;")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_13.setGeometry(QtCore.QRect(665, 175, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setStyleSheet("\n"
"    background-color: rgb(186, 201, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(150, 175, 255) ;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"")
        self.lineEdit_13.setText("")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_14.setGeometry(QtCore.QRect(665, 415, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setStyleSheet("    background-color: rgb(186, 201, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(150, 175, 255) ;\n"
"    min-width: 10em;\n"
"    padding: 6px;")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_20 = QtWidgets.QLabel(self.page_2)
        self.label_20.setGeometry(QtCore.QRect(470, 300, 146, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("font-weight: bold;")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.page_2)
        self.label_21.setGeometry(QtCore.QRect(470, 425, 146, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("font-weight: bold;")
        self.label_21.setObjectName("label_21")
        self.label_16 = QtWidgets.QLabel(self.page_2)
        self.label_16.setGeometry(QtCore.QRect(470, 180, 146, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("font-weight: bold;")
        self.label_16.setObjectName("label_16")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_15.setGeometry(QtCore.QRect(665, 475, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setStyleSheet("    background-color: rgb(186, 201, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(150, 175, 255) ;\n"
"    min-width: 10em;\n"
"    padding: 6px;")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_16.setGeometry(QtCore.QRect(665, 355, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setStyleSheet("    background-color: rgb(186, 201, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(150, 175, 255) ;\n"
"    min-width: 10em;\n"
"    padding: 6px;")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_22 = QtWidgets.QLabel(self.page_2)
        self.label_22.setGeometry(QtCore.QRect(470, 245, 146, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("font-weight: bold;")
        self.label_22.setObjectName("label_22")
        self.label_18 = QtWidgets.QLabel(self.page_2)
        self.label_18.setGeometry(QtCore.QRect(470, 485, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("font-weight: bold;")
        self.label_18.setObjectName("label_18")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_17.setGeometry(QtCore.QRect(665, 235, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_17.setFont(font)
        self.lineEdit_17.setStyleSheet("\n"
"    background-color: rgb(186, 201, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(150, 175, 255) ;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"")
        self.lineEdit_17.setText("")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_19 = QtWidgets.QLabel(self.page_2)
        self.label_19.setGeometry(QtCore.QRect(560, 90, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("")
        self.label_19.setObjectName("label_19")
        self.label_17 = QtWidgets.QLabel(self.page_2)
        self.label_17.setGeometry(QtCore.QRect(470, 360, 146, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("font-weight: bold;")
        self.label_17.setObjectName("label_17")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_3.setGeometry(QtCore.QRect(600, 540, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bebas")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("#pushButton_3{    background-color: rgb(13, 67, 212);\n"
"color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#pushButton_3:pressed{     background-color: rgb(0, 20, 212); }")
        self.pushButton_3.setObjectName("pushButton_3")
        self.comboBox = QtWidgets.QComboBox(self.page_2)
        self.comboBox.setGeometry(QtCore.QRect(60, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox::drop-down {\n"
"    background-color:rgb(220,220,220)\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"    border:none;\n"
"     border-left-width: 1px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"QComboBox{    background-color:rgb(220,220,220)}\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_5.setGeometry(QtCore.QRect(530, 600, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: none;\n"
"border:none;\n"
"\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.stackedWidget.addWidget(self.page_2)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_7.setGeometry(QtCore.QRect(660, 475, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("    background-color: rgb(186, 201, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(150, 175, 255) ;\n"
"    min-width: 10em;\n"
"    padding: 6px;")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_9 = QtWidgets.QLabel(self.page)
        self.label_9.setGeometry(QtCore.QRect(585, 90, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("")
        self.label_9.setObjectName("label_9")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_8.setGeometry(QtCore.QRect(660, 295, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("    background-color: rgb(186, 201, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(150, 175, 255) ;\n"
"    min-width: 10em;\n"
"    padding: 6px;")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.page)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 540, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bebas")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("#pushButton_2{    background-color: rgb(13, 67, 212);\n"
"color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#pushButton_2:pressed{     background-color: rgb(0, 20, 212); }")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_9.setGeometry(QtCore.QRect(660, 175, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet("#lineEdit_9 {\n"
"    background-color: rgb(186, 201, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(150, 175, 255) ;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_10 = QtWidgets.QLabel(self.page)
        self.label_10.setGeometry(QtCore.QRect(500, 180, 146, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("font-weight: bold;")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.page)
        self.label_11.setGeometry(QtCore.QRect(500, 245, 146, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("font-weight: bold;")
        self.label_11.setObjectName("label_11")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_10.setGeometry(QtCore.QRect(660, 415, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setStyleSheet("    background-color: rgb(186, 201, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(150, 175, 255) ;\n"
"    min-width: 10em;\n"
"    padding: 6px;")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_12 = QtWidgets.QLabel(self.page)
        self.label_12.setGeometry(QtCore.QRect(500, 300, 146, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("font-weight: bold;")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.page)
        self.label_13.setGeometry(QtCore.QRect(500, 425, 146, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("font-weight: bold;")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.page)
        self.label_14.setGeometry(QtCore.QRect(500, 485, 146, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("font-weight: bold;")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.page)
        self.label_15.setGeometry(QtCore.QRect(500, 360, 146, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("font-weight: bold;")
        self.label_15.setObjectName("label_15")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_11.setGeometry(QtCore.QRect(660, 355, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setStyleSheet("    background-color: rgb(186, 201, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(150, 175, 255) ;\n"
"    min-width: 10em;\n"
"    padding: 6px;")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_12.setGeometry(QtCore.QRect(660, 235, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setStyleSheet("#lineEdit_12 {\n"
"    background-color: rgb(186, 201, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(150, 175, 255) ;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.comboBox_2 = QtWidgets.QComboBox(self.page)
        self.comboBox_2.setGeometry(QtCore.QRect(60, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("QComboBox::drop-down {\n"
"    background-color:rgb(220,220,220)\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"    border:none;\n"
"     border-left-width: 1px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"QComboBox{    background-color:rgb(220,220,220)}\n"
"")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.pushButton_8 = QtWidgets.QPushButton(self.page)
        self.pushButton_8.setGeometry(QtCore.QRect(560, 600, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: none;\n"
"border:none;\n"
"\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.stackedWidget.addWidget(self.page_3)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1481, 121))
        self.widget.setStyleSheet("background-color:#0d43d4")
        self.widget.setObjectName("widget")
        self.label_50 = QtWidgets.QLabel(self.widget)
        self.label_50.setGeometry(QtCore.QRect(140, 20, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue")
        font.setPointSize(48)
        font.setBold(False)
        font.setWeight(50)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("")
        self.label_50.setObjectName("label_50")
        self.label_53 = QtWidgets.QLabel(self.widget)
        self.label_53.setGeometry(QtCore.QRect(20, 0, 121, 121))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label_53.setFont(font)
        self.label_53.setStyleSheet("")
        self.label_53.setObjectName("label_53")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_40.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">DNI</span></p></body></html>"))
        self.label_42.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Contraseña</span></p></body></html>"))
        self.label_43.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Nombre</span></p></body></html>"))
        self.label_46.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Ingresar</p></body></html>"))
        self.pushButton_6.setText(_translate("MainWindow", "ACEPTAR"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Español"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "English"))
        self.pushButton_9.setText(_translate("MainWindow", "¿No estás registrado? Regístrate"))
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Name</span></p></body></html>"))
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">ID</span></p></body></html>"))
        self.label_47.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Password</span></p></body></html>"))
        self.pushButton_7.setText(_translate("MainWindow", "LOG IN"))
        self.label_48.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">log in</p></body></html>"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "English"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Español"))
        self.pushButton_10.setText(_translate("MainWindow", "Aren\'t you registered? Sign Up"))
        self.label_52.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Bienvenido al sistema</p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Nombre</span></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">JorgitoPérez</span></p><p><br/></p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Mail</span></p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">jorgitoperez@gmail.com</span></p><p><br/></p></body></html>"))
        self.pushButton_4.setText(_translate("MainWindow", "Volver"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">DNI</span></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Contraseña</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Nombre</span></p></body></html>"))
        self.lineEdit_16.setText(_translate("MainWindow", "* Opcional"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Apellido</span></p><p><br/></p><p><br/></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Confirmar Contraseña</span></p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">regístrate</p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Mail</span></p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "ACEPTAR"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Español"))
        self.comboBox.setItemText(1, _translate("MainWindow", "English"))
        self.pushButton_5.setText(_translate("MainWindow", "¿Ya estás registrado? Inicia sesión"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">SIGN UP</p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "ENTER"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Forename</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Surname</span></p><p><br/></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">ID</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Password</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Confirm Password</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Mail</span></p></body></html>"))
        self.lineEdit_11.setText(_translate("MainWindow", "* Optional"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "English"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Español"))
        self.pushButton_8.setText(_translate("MainWindow", "Already registered? Log In"))
        self.label_50.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">duraam</span></p></body></html>"))
        self.label_53.setText(_translate("MainWindow", f"<html><head/><body><p><img src=\"{os.path.abspath(os.getcwd())}/duraam/images/bitmap.png\"/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
